Check disposable properties after its creation
Exception raised on invalid qube name instead of a proper message that
qube does not exist, added in cc9c5f52f2d4e8f2412db49e7cdb5eda8284dc62.

$ time qvm-run -p -v --dispvm=unexistent -- echo hi
Traceback (most recent call last):
  File "/usr/bin/qvm-run", line 5, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/lib/python3.13/site-packages/qubesadmin/tools/qvm_run.py", line 367, in main
    else args.app.domains[args.dispvm]
         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/qubesadmin/app.py", line 108, in __getitem__
    raise KeyError(item)
KeyError: 'unexistent'

The second problem is checking for the features and properties of the
disposable template at the current time, it may not reflect the features
and properties of the received disposable, because of preloaded
disposables.

Fixes: https://github.com/qubesos/qubes-issues/issues/10383
For: https://github.com/qubesos/qubes-issues/issues/1512