Call qvm_shutdown module from template postprocess
I tried to not require async functions, by passing the loop from
template_postprocess to qvm_shutdown.main, but failed with:

        RuntimeError: This event loop is already running